### ISSUE TITLE
responsividade

### ISSUE THREAD

**Issue by giovannalovate** [luana8mai/carolino#3]
as fotos e textos da página sobre nós não estão responsivas, prejudicando a estética do site

**Comment by fmcarreiro** [comment]
o menu superior está 'quebrando' em tamanho de telas menores (mobile)

![image](https://user-images.githubusercontent.com/133460/197222943-60613968-b049-43f0-ba18-5dca19f42039.png)

**Comment by fmcarreiro** [comment]
> as fotos e textos da página sobre nós não estão responsivas, prejudicando a estética do site

![image](https://user-images.githubusercontent.com/133460/197224129-69a88e6c-48e7-4fba-b182-b794cfd64aa7.png)
